# Generated by Django 5.0.7 on 2024-07-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
